[package]
name = "shrimpql"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
lalrpop-util = { version = "0.22.2", features = ["lexer", "unicode"] }
logos = { version = "0.15.1", features = ["debug"] }

[build-dependencies]
lalrpop = "0.22.2"
